name: Publish Docker

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the action on"
        default: "agency"
        required: true

jobs:
  build_and_publish:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        app:
          - name: usesend
            dockerfile: ./docker/Dockerfile
            context: .
          - name: smtp-proxy
            dockerfile: ./apps/smtp-server/Dockerfile
            context: ./apps/smtp-server

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        env:
          APP: ${{ matrix.app.name }}
          DOCKER_FILE: ${{ matrix.app.dockerfile }}
          CONTEXT: ${{ matrix.app.context }}
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          docker build \
            -f "$DOCKER_FILE" \
            --progress=plain \
            --build-arg APP_VERSION="$APP_VERSION" \
            --build-arg GIT_SHA="$GIT_SHA" \
            -t "ghcr.io/alisamadiii/$APP:latest" \
            -t "ghcr.io/alisamadiii/$APP:$GIT_SHA" \
            -t "ghcr.io/alisamadiii/$APP:$APP_VERSION" \
            "$CONTEXT"

      - name: Push the docker image to GitHub Container Registry
        run: docker push --all-tags "ghcr.io/alisamadiii/$APP"
        env:
          APP: ${{ matrix.app.name }}
